
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__client_proxy_h__proxy__H__
#define __sdbuscpp__client_proxy_h__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace com {
namespace example {

class Interface_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "com.example.Interface";

protected:
    Interface_proxy(sdbus::IProxy& proxy)
        : proxy_(&proxy)
    {
        proxy_->uponSignal("ProcessUpdated").onInterface(INTERFACE_NAME).call([this](const sdbus::Struct<int32_t, std::string, double, double, uint64_t, uint8_t, uint64_t, std::string>& process){ this->onProcessUpdated(process); });
    }

    Interface_proxy(const Interface_proxy&) = delete;
    Interface_proxy& operator=(const Interface_proxy&) = delete;
    Interface_proxy(Interface_proxy&&) = default;
    Interface_proxy& operator=(Interface_proxy&&) = default;

    ~Interface_proxy() = default;

    virtual void onProcessUpdated(const sdbus::Struct<int32_t, std::string, double, double, uint64_t, uint8_t, uint64_t, std::string>& process) = 0;

private:
    sdbus::IProxy* proxy_;
};

}} // namespaces

#endif
