
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__server_adaptor_h__adaptor__H__
#define __sdbuscpp__server_adaptor_h__adaptor__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace com {
namespace example {

class Interface_adaptor
{
public:
    static constexpr const char* INTERFACE_NAME = "com.example.Interface";

protected:
    Interface_adaptor(sdbus::IObject& object)
        : object_(&object)
    {
        object_->registerSignal("ProcessUpdated").onInterface(INTERFACE_NAME).withParameters<sdbus::Struct<int32_t, std::string, double, double, uint64_t, uint8_t, uint64_t, std::string>>("process");
    }

    Interface_adaptor(const Interface_adaptor&) = delete;
    Interface_adaptor& operator=(const Interface_adaptor&) = delete;
    Interface_adaptor(Interface_adaptor&&) = default;
    Interface_adaptor& operator=(Interface_adaptor&&) = default;

    ~Interface_adaptor() = default;

public:
    void emitProcessUpdated(const sdbus::Struct<int32_t, std::string, double, double, uint64_t, uint8_t, uint64_t, std::string>& process)
    {
        object_->emitSignal("ProcessUpdated").onInterface(INTERFACE_NAME).withArguments(process);
    }

private:
    sdbus::IObject* object_;
};

}} // namespaces

#endif
